sudo: false
language: ruby
matrix:
  include:
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.1
    - rvm: 2.4.0-preview2
  allow_failures:
    - rvm: 2.4.0-preview2
before_install:
  - gem install bundler
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
